### ISSUE TITLE
Fatal error: Uncaught Error: Class "VisitorLog" not found

### ISSUE THREAD

**Issue by idhamari** [clbonner/VisitorLog#1]
Hi thanks for your effort. I created your class in a file /VisitorLog.php then I used it in html web page like this 

         include("./VisitorLog.php");
         use VisitorLog;
         $visitor = new VisitorLog(true);
         $visitor->log();

I got this error:  

                Warning: session_start(): Session cannot be started after headers have already been sent in 
                /var/www/myweb/VisitorLog.php on line 11

                Fatal error: Uncaught Error: Class "VisitorLog" not found in /var/www/myweb/index.php:40 Stack 
                 trace: #0 {main} thrown in /var/www/myweb/index.php on line 40

**Comment by clbonner** [comment]
Hi,

I have updated the source code. Make sure you put session_start() at the beginning of your code. I had left it in there accidently from testing.

The use statement should have been use VisitorLog\VisitorLog;

Thanks.
